### ISSUE TITLE
How to code Instrument Settings with multiple Parameters

### ISSUE THREAD

**Issue by moritzj29** [ralph-group/pymeasure#224]
Hi,
I'm starting my way with pymeasure and try to implement one of our instruments. Unfortunately, a lot of commands take two or more input arguments. E.g. `AIT type, mode, N`
As I understand, the preferred way to implement settings is to use Python properties. Either with the predefined functions measurement/setting/control or by setting up a custom property. But properties can only take one argument. What is the preferred way of implementing settings with two or more arguments?

One idea would be to just use methods like `instrument.ait(type,mode,N)` but this would break the syntax compared to using properties, right?
Or one could pass the arguments as a tuple to the property: `instrument.ait = (type,mode,N)` This is not as elegant in my opinion, since you are missing out on named arguments, etc..

Do you have any idea how to handle this issue in a good way? It's been some time since my last Python coding, so maybe I'm just missing out on something...

**Comment by bilderbuchi** [comment]
I think methods are your best bet, here. Properties are primarily useful because they simplify the interface for mainly simple things, which are possibly "symmetric" (for want of a better word) in getting/setting. Compare
```
voltage = instr.get_voltage()
instr.set_voltage(voltage + 2)
``` 
to
```
voltage = instr.voltage
instr.voltage = voltage + 2
```
For more complex things, I would just go with methods. Also, in your example, I am assuming that the in/out symmetry is not preserved, i.e. "getting" `ait` would not make sense at all or yield more than one value?

**Comment by moritzj29** [comment]
thanks for your fast reply! You are absolutely correct, "getting" is not even possible for those commands. So I will go with methods here.

**Comment by bilderbuchi** [comment]
Happy to help 😄
